version: '3.8'
services:
  hotspot:
    build: .
    container_name: hotspot-pix
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./vouchers.db:/app/vouchers.db
      - ./logs:/app/logs
      - ./static/qrcodes:/app/static/qrcodes
    env_file:
      - .env
